### PR TITLE
fixing non-ASCII redirects from issue #42

### LINKED ISSUE #42: non-ASCII characters allowed don't redirect
Emojis and chars like the horizontal ellipsis `…` can be submitted successfully in the FROM path's, but they don't actually redirect.

This could be a problem if for example this plugin is used as a shortener by marketers, ie: `/🔥-deals`

### PR DESCRIPTION
**Pull request by ovidiul**
This PR addressed the bug highlighted in issue #42 

It adds:
- the main fix includes replacing the wp_parse_url method with a helper method called `mb_parse_url` that properly handles non-ASCII chars encodings
- a new `Utils` class to keep helper method mb_parse_url
- a new tests class `UtilsTest` for the Utils class
- it refactors the `maybe_do_redirect` method by adding a `Lookup::get_redirect_data` method for easier testing; this will also decrease its overall cyclomatic code complexity
- it adds a few tests for the `Lookup::get_redirect_data` method in the `LookupTest` class

### CODE REVIEW

File: includes/class-utils.php [hunk 1]
```diff
@@ -0,0 +1,46 @@
+<?php
+
+namespace Automattic\LegacyRedirector;
+
+final class Utils {
+
+    /**
```
Comment (GaryJones) [inline includes/class-utils.php]: This line has 4 space indentation, rather than 1 tab.

File: includes/class-lookup.php [hunk 2]
```diff
@@ -103,6 +105,42 @@ public static function get_preservable_querystring_params_from_url( $url ) {
 		return array_intersect_key( $url_params, array_flip( $preservable_param_keys ) );
 	}
 
+		/**
+		 * Get redirect data status and url based on the provided url
+		 *
+		 * @param string $url
```
Comment (GaryJones) [inline includes/class-lookup.php]: Needs a description.

File: includes/class-lookup.php [hunk 3]
```diff
@@ -103,6 +105,42 @@ public static function get_preservable_querystring_params_from_url( $url ) {
...
+		 *
+		 * @return false|array
```
Comment (GaryJones) [inline includes/class-lookup.php]: No line space between `@param` and `@return`.

Needs a description.

File: includes/class-utils.php [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+			foreach ( $parts as $name => $value ) {
+				$parts[ $name ] = urldecode( $value );
+			}
+		} else {
+			$parts = urldecode( $parts );
+		}
+
+		return $parts;
+	}
+}
```
Comment (GaryJones) [inline includes/class-utils.php]: Needs a clear linespace after the `}`.

File: includes/class-utils.php [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+
+final class Utils {
+
+    /**
+	 * UTF-8 aware parse_url() replacement.
+	 *
+	 * @throws \InvalidArgumentException Malformed URL.
+	 * 
+	 * @param string $url       The URL to parse.
+	 * @param int    $component The specific component to retrieve. Use one of the
```
Comment (GaryJones) [inline includes/class-utils.php]:
```suggestion
	 * @param int    $component Optional. The specific component to retrieve. Use one of the
```

File: includes/class-utils.php [hunk 6]
```diff
@@ -0,0 +1,46 @@
+<?php
+
+namespace Automattic\LegacyRedirector;
+
+final class Utils {
```
Comment (GaryJones) [inline includes/class-utils.php:5]: Instead of a Utils class, how about a `Url` class, that could be instantiated (avoiding static methods), and then have methods for `normalize` (can defer to a constructor dependency injection of a `Normalizer` interface), `hasher` (can defer to a constructor dependency injection of a `Hasher` interface), `get_preservable_querystring_params()`, and then this `->mb_parse_url( $components )` method?

(Might be easier to go with Utils for now, but then refactor again)

File: includes/class-wpcom-legacy-redirector.php [hunk 7]
```diff
@@ -306,9 +303,9 @@ public static function check_if_404( $url ) {
...
 			// If it was an error, try again with no SSL verification, in case it was a self-signed certificate: https://github.com/Automattic/WPCOM-Legacy-Redirector/issues/64.
 			if ( is_wp_error( $response ) ) {
-				$args     = [
+				$args     = array(
 					'sslverify' => false,
-				];
+				);
 				$response = wp_remote_get( $url, $args );
 			}
 		}
```
Comment (GaryJones) [inline includes/class-wpcom-legacy-redirector.php]: The file below is a CapabilityTest.php - should that be in this PR?

File: tests/Unit/MonkeyStubs.php [hunk 8]
```diff
@@ -0,0 +1,18 @@
+<?php
+
+namespace Automattic\LegacyRedirector\Tests\Unit;
+
+use Brain\Monkey;
+
+final class MonkeyStubs {
+
+    public function __construct() {
+        Monkey\Functions\stubs(
```
Comment (GaryJones) [inline tests/Unit/MonkeyStubs.php]: Indented with spaces.

File: tests/Unit/MonkeyStubs.php [hunk 9]
```diff
@@ -0,0 +1,18 @@
...
+			array(
+				'wp_parse_url' => static function ( $url, $component ) {
+					return parse_url( $url, $component );
+				},
+			)
+		);
+    }
```
Comment (GaryJones) [inline tests/Unit/MonkeyStubs.php]: Indented with spaces.

File: tests/Unit/UtilsTest.php [hunk 10]
```diff
@@ -0,0 +1,81 @@
...
+	 */
+	public function test_mb_parse_url() {
+
+		Monkey\Functions\stubs(
+			array(
+				'wp_parse_url' => static function ( $url, $component ) {
+					return parse_url( $url, $component );
+				},
+			)
+		);
```
Comment (GaryJones) [inline tests/Unit/UtilsTest.php]: This stub is also defined in MonkeyStubs - does there need to be the duplicate?

File: tests/Unit/UtilsTest.php [hunk 11]
```diff
@@ -0,0 +1,81 @@
...
+		$this->do_assetion_mb_parse_url( $url, 'https', 'www.example.com', '/test', '' );
+
+		$url = 'http://www.example.com//فوتوغرافيا/?test=فوتوغرافيا';
+		$this->do_assetion_mb_parse_url( $url, 'http', 'www.example.com', '//فوتوغرافيا/', 'test=فوتوغرافيا' );
+
+		$url = '/فوتوغرافيا/?test=فوتوغرافيا';
+		$this->do_assetion_mb_parse_url( $url, '', '', '/فوتوغرافيا/', 'test=فوتوغرافيا' );
+
+		$url = '/فوتوغرافيا/?test2=فوتوغرافيا&test=فوتوغرافيا';
+		$this->do_assetion_mb_parse_url( $url, '', '', '/فوتوغرافيا/', 'test2=فوتوغرافيا&test=فوتوغرافيا' );
```
Comment (GaryJones) [inline tests/Unit/UtilsTest.php]: Seems like these values should be held in a dataProvider method?

File: tests/Unit/UtilsTest.php [hunk 12]
```diff
@@ -0,0 +1,81 @@
...
+	 * Do assertion method for testing mb_parse_url
+	 *
+	 * @param string $url
+	 * @param string $expected_scheme
+	 * @param string $expected_host
+	 * @param string $expected_path
+	 * @param string $expected_query
+	 * @return void
+	 */
+	private function do_assetion_mb_parse_url( $url, $expected_scheme, $expected_host, $expected_path, $expected_query ) {
```
Comment (GaryJones) [inline tests/Unit/UtilsTest.php]: Typo: assetion -> assertion

File: tests/Unit/UtilsTest.php [hunk 13]
```diff
@@ -0,0 +1,81 @@
...
+	}
+
+	/**
+	 * Do assertion method for testing mb_parse_url
+	 *
+	 * @param string $url
+	 * @param string $expected_scheme
+	 * @param string $expected_host
+	 * @param string $expected_path
+	 * @param string $expected_query
```
Comment (GaryJones) [inline tests/Unit/UtilsTest.php]: Need descriptions.

File: tests/Unit/UtilsTest.php [hunk 14]
```diff
@@ -0,0 +1,81 @@
...
+		$url = '/فوتوغرافيا/?test=فوتوغرافيا';
+		$this->do_assetion_mb_parse_url( $url, '', '', '/فوتوغرافيا/', 'test=فوتوغرافيا' );
+
+		$url = '/فوتوغرافيا/?test2=فوتوغرافيا&test=فوتوغرافيا';
+		$this->do_assetion_mb_parse_url( $url, '', '', '/فوتوغرافيا/', 'test2=فوتوغرافيا&test=فوتوغرافيا' );
+
+	}
+
+	/**
+	 * Do assertion method for testing mb_parse_url
```
Comment (GaryJones) [inline tests/Unit/UtilsTest.php]:
```suggestion
	 * Do assertion method for testing mb_parse_url().
```

File: tests/Unit/UtilsTest.php [hunk 15]
```diff
@@ -0,0 +1,81 @@
...
+		}
+		if ( ! isset( $path_info['path'] ) ) {
+			$path_info['path'] = '';
+		}
+		if ( ! isset( $path_info['query'] ) ) {
+			$path_info['query'] = '';
+		}
+
+		$this->assertTrue( is_array( $path_info ) );
+		$this->assertTrue( sizeof( $path_info ) > 1 ? true : false );
```
Comment (GaryJones) [inline tests/Unit/UtilsTest.php]:
```suggestion
		$this->assertTrue( count( $path_info ) > 1 ? true : false );
```

File: tests/Integration/RedirectsTest.php [hunk 16]
```diff
@@ -25,11 +37,6 @@ public function get_redirect_data() {
 				'http://example.com',
 			),
 
-			'redirect_unicode_in_path'  => array(
-				// https://www.w3.org/International/articles/idn-and-iri/
-				'/JP納豆',
-				'http://example.com',
-			),
 		);
 	}
```
Comment (GaryJones) [inline tests/Integration/RedirectsTest.php:58]: The `tests/Integration/bootstrap.php` file below has apparently only got 1 addition, but is too large to be shown?!

**Review by GaryJones — CHANGES_REQUESTED** [review]
I like where this is heading :-)

File: includes/class-utils.php (hunk 6 above)
Comment (ovidiul) [reply includes/class-utils.php:5]: I agree here, I have a feeling we will have much more confidence with refactoring as we add more unit/integration tests, it would be a good test against the validity of the tests as well :)

File: includes/class-utils.php (hunk 1 above)
Comment (ovidiul) [reply includes/class-utils.php]: fixed

File: tests/Integration/RedirectsTest.php (hunk 16 above)
Comment (ovidiul) [reply tests/Integration/RedirectsTest.php:58]: It was a missing line, in the end, should be fixed now as well.

File: tests/Unit/UtilsTest.php (hunk 10 above)
Comment (ovidiul) [reply tests/Unit/UtilsTest.php]: added a fix here to get the stub from the MonkeyStub class, I see it used in the PreservableParamsTest test as well, so we might as well just share it.

File: tests/Unit/UtilsTest.php (hunk 11 above)
Comment (ovidiul) [reply tests/Unit/UtilsTest.php]: added a new data provider for it.

File: includes/class-wpcom-legacy-redirector.php (hunk 7 above)
Comment (ovidiul) [reply includes/class-wpcom-legacy-redirector.php]: I am missing the file indication here, are you referring to the UtilsTest class?

File: phpunit.xml.dist [hunk 17]
```diff
@@ -20,6 +20,10 @@
 		stopOnSkipped="false"
 		verbose="true"
 	>
+	<php>
+        <ini name="display_errors" value="On" />
+        <ini name="display_startup_errors" value="On" />
+    </php>
```
Comment (GaryJones) [inline phpunit.xml.dist]: These lines use spaces for indentation.

Can these changes be moved to a new PR?

File: tests/Integration/LookupTest.php [hunk 18]
```diff
@@ -10,10 +10,14 @@
...
 	/**
-	 * Test Lookup::get_redirect_uri
+	 * Test Lookup::get_redirect_uri.
 	 *
 	 * @covers Lookup::get_redirect_uri
 	 * @dataProvider get_protected_redirect_data
+	 *
+	 * @param [type] $from_url        Redirect From URL.
+	 * @param [type] $to_url          Redirect To URL.
+	 * @param [type] $redirect_status Redirect Status Code.
```
Comment (GaryJones) [inline tests/Integration/LookupTest.php]: The types need populating.

File: tests/Unit/UtilsTest.php [hunk 19]
```diff
@@ -4,45 +4,92 @@
...
-				},
-			)
-		);
-
-		$url = 'https://www.example.org';
-		$this->do_assertion_mb_parse_url( $url, 'https', 'www.example.org', '', '' );
-
-		$url = 'https://www.example.org/';
-		$this->do_assertion_mb_parse_url( $url, 'https', 'www.example.org', '/', '' );
+	public static function initialSetup() {
```
Comment (GaryJones) [inline tests/Unit/UtilsTest.php]:
```suggestion
	public static function set_up() {
```

Try to get a bit of consistency with the usual naming.

File: tests/Unit/UtilsTest.php [hunk 20]
```diff
@@ -4,45 +4,92 @@
...
+		new MonkeyStubs();
```
Comment (GaryJones) [inline tests/Unit/UtilsTest.php]: You probably need to call `parent::setUp()` or `parent::set_up()` in this as well so that Brain Monkey is also configured correctly.

File: tests/Unit/UtilsTest.php [hunk 21]
```diff
@@ -4,45 +4,92 @@
...
+	 * Tests Utils::mb_parse_url().
+	 *
+	 * @dataProvider get_protected_redirect_data
+	 * @covers \Automattic\LegacyRedirector\Utils::mb_parse_url
+	 *
+	 * @param [type] $url             Full URL to parse.
+	 * @param [type] $expected_schema Expected return schema.
+	 * @param [type] $expected_domain Expected return domain.
+	 * @param [type] $expected_path   Expected return path.
+	 * @param [type] $expected_query  Expected return query.
```
Comment (GaryJones) [inline tests/Unit/UtilsTest.php]: Types need populating.

**Review by GaryJones — CHANGES_REQUESTED** [review]

File: includes/class-wpcom-legacy-redirector.php [hunk 22]
```diff
@@ -65,30 +66,26 @@ static function maybe_do_redirect() {
...
-				$redirect_status = apply_filters( 'wpcom_legacy_redirector_redirect_status', 301, $url );
-
-				// Third argument introduced to support the x_redirect_by header to denote WP redirect source.
-				if ( version_compare( get_bloginfo( 'version' ), '5.1.0', '>=' ) ) {
-					wp_safe_redirect( $redirect_uri, $redirect_status, WPCOM_LEGACY_REDIRECTOR_PLUGIN_NAME );
-				} else {
-					header( 'X-legacy-redirect: HIT' );
-					wp_safe_redirect( $redirect_uri, $redirect_status );
-				}
+		if ( ! $redirect_data || ! isset( $redirect_data['redirect_uri'] ) ) {
```
Comment (GaryJones) [inline includes/class-wpcom-legacy-redirector.php:82]: It's OK to leave for now, but this line is now directly coupled into the keys used into the return of the `Lookup::get_redirect_data()` (specifically, `redirect_uri`).

Ideally, we'd have an object returned for that, which could have a suitable method on it which hid the implementation of the data structure.

File: includes/class-wpcom-legacy-redirector.php [hunk 23]
```diff
@@ -65,30 +66,26 @@ static function maybe_do_redirect() {
...
-				exit;
-			}
+			// Third argument introduced to support the x_redirect_by header to denote WP redirect source.
+		if ( version_compare( get_bloginfo( 'version' ), '5.1.0', '>=' ) ) {
+			wp_safe_redirect( $redirect_data['redirect_uri'], $redirect_data['redirect_status'], WPCOM_LEGACY_REDIRECTOR_PLUGIN_NAME );
+		} else {
+			header( 'X-legacy-redirect: HIT' );
+			wp_safe_redirect( $redirect_data['redirect_uri'], $redirect_data['redirect_status'] );
 		}
+
```
Comment (GaryJones) [inline includes/class-wpcom-legacy-redirector.php:93]: Looks like the `exit;` has been removed from this method. There should always be an `exit;` after redirect headers are sent to ensure that the current request is killed and the redirect acted on.

File: includes/class-wpcom-legacy-redirector.php [hunk 24]
```diff
@@ -227,13 +224,13 @@ public static function get_url_hash( $url ) {
 	 */
 	public static function normalise_url( $url ) {
 		// Sanitise the URL first rather than trying to normalise a non-URL.
-		$url = esc_url_raw( $url );
+		$url = esc_url_raw( wp_unslash( $url ) );
```
Comment (GaryJones) [inline includes/class-wpcom-legacy-redirector.php]: Is there a unit test that shows the effect this change has?

What would happen to saved redirects that had extra slashes in it? Would they no longer work?

File: includes/class-wpcom-legacy-redirector.php (hunk 7 above)
Comment (GaryJones) [reply includes/class-wpcom-legacy-redirector.php]: No, the `CapabilityTest.php` file - has extra spaces added to it, which seem unrelated to the changes in the PR.

We're not yet testing against coding standards as part of the build step, and even if we were, whitespace / coding style changes should go into their own PR.

File: tests/Unit/MonkeyStubs.php [hunk 25]
```diff
@@ -0,0 +1,18 @@
...
+
+	public function __construct() {
+		Monkey\Functions\stubs(
+			array(
+				'wp_parse_url' => static function ( $url, $component ) {
+					return parse_url( $url, $component );
+				},
+			)
+		);
+	}
```
Comment (GaryJones) [inline tests/Unit/MonkeyStubs.php]: Rather than a class which is just used to add new stubs, I wonder if it makes more sense to create a custom unit test case (`WPStubbedTestCase`), like https://github.com/Yoast/wp-test-utils/blob/develop/src/BrainMonkey/YoastTestCase.php and perhaps extended from it to save having to re-define the WP stubs it already defines.

That way, instead of `final class UtilsTest extends use Yoast\WPTestUtils\BrainMonkey\TestCase {` it would be `final class UtilsTest extends use Automattic\LegacyRedirector\Tests\Unit\WPStubbedTestCase {`

That would then allow removal of the `UtilsTest::set_up()` as well.

**Review by GaryJones — CHANGES_REQUESTED** [review]

File: includes/class-wpcom-legacy-redirector.php (hunk 23 above)
Comment (ovidiul) [reply includes/class-wpcom-legacy-redirector.php:93]: done, added a comment there to prevent future removal.

File: includes/class-wpcom-legacy-redirector.php (hunk 24 above)
Comment (ovidiul) [reply includes/class-wpcom-legacy-redirector.php]: I did add a new test under UtilsTest->test_normalise_url which should be able to clear this. 

So, the `wp_unslash` does not remove the extra slashes, but the redirection only works if the exact path is matched, so it needs to include any additional slashes, do we need to reconsider this?

File: tests/Unit/MonkeyStubs.php (hunk 25 above)
Comment (ovidiul) [reply tests/Unit/MonkeyStubs.php]: makes sense, I am now extending class `YoastTestCase` from `MonkeyStubs` and I could remove the `UtilsTest::set_up()`

File: includes/class-wpcom-legacy-redirector.php (hunk 22 above)
Comment (ovidiul) [reply includes/class-wpcom-legacy-redirector.php:82]: The `Lookup` class might actually need to be renamed to `Redirect` class as I see most of its methods would relate to that.

File: includes/class-wpcom-legacy-redirector.php (hunk 24 above)
Comment (GaryJones) [reply includes/class-wpcom-legacy-redirector.php]: There are two points here - what the ideal situation would be, and what we currently need to maintain so that existing saved redirects continue to work. Changing how URLs are normalised worries me that we're going to break existing redirects.

Does the non-ascii redirects NEED this unslashing change?

File: includes/class-wpcom-legacy-redirector.php (hunk 22 above)
Comment (GaryJones) [reply includes/class-wpcom-legacy-redirector.php:82]: I disagree - a `Redirect` is something that lives in the domain - it is an object that exists regardless of where the data for it is persisted. 

The Lookup, so far, is about the "concrete" implementation that says to look in the database.

Having an abstraction layer between the thing and where it lives, means we move towards a future that could store the redirects in a custom table, rather than the wp_posts table, or in memory for unit test purposes.

File: includes/class-utils.php [hunk 26]
```diff
@@ -44,4 +44,47 @@ function ( $matches ) {
...
 	}
 
+	/**
+	 * Takes a request URL and "normalises" it, stripping common elements.
+	 * Removes scheme and host from the URL, as redirects should be independent of these.
+	 *
+	 * @param string $url URL to transform.
+	 * @return string|WP_Error Transformed URL; error if validation failed.
+	 */
+	public static function normalise_url( $url ) {
```
Comment (GaryJones) [inline includes/class-utils.php]: Moving this method isn't needed for this PR.

Comment (GaryJones) [reply includes/class-utils.php]: I'd like to a point where this behaviour is extracted into it's own service class:

```php
interface Url_Normalizer {
	public function normalize( $url );
}

class Default_Url_Normalizer implements Url_Normalizer {
	public function normalize( $url ) {
		...
	}
}
```

Then we can have a URL class that can accept an `Url_Normalizer`, and be passed an instance of `Default_Url_Normalizer` for normal running, or a mock object for testing.

This concrete implementation could have a filter wrapped around it, so if customers want to provide their own concrete implementation that handled normalizing in a different way, they could.

File: includes/class-wpcom-legacy-redirector.php (hunk 24 above)
Comment (ovidiul) [reply includes/class-wpcom-legacy-redirector.php]: I've added the wp_unslash() for better sanitization, but it might as well be removed since we decompose the URL using `mb_parse_url` method.

I did add a few more tests to handle non-ASCII multiple slashes redirects, and I don't see it affecting the previous logic.

I think it's better to address your concern with a Functional test, maybe a CLI command that would run against the redirects found in the database, and then we apply the `Lookup::get_redirect_data` method to check the output, I think this will give us better confidence when dealing with a large number of redirects setup in knowing if we would break existing ones.

File: includes/class-utils.php (hunk 26 above)
Comment (ovidiul) [reply includes/class-utils.php]: Reverted code change and added a new Unit test class `RedirectsTests` to keep the unit tests for `normalize_url`

File: includes/class-wpcom-legacy-redirector.php (hunk 24 above)
Comment (ovidiul) [reply includes/class-wpcom-legacy-redirector.php]: removed the `wp_unslash` call for now.

File: phpunit.xml.dist [hunk 27]
```diff
@@ -20,10 +20,6 @@
 		stopOnSkipped="false"
 		verbose="true"
 	>
-	<php>
-        <ini name="display_errors" value="On" />
-        <ini name="display_startup_errors" value="On" />
-    </php>
```
Comment (GaryJones) [inline phpunit.xml.dist]: @ovidiul It seems like you're adding this while working, and then it's getting committed accidentally?

Copy `phpunit.xml.dist` to `phpunit.xml` and then add these ini lines to `phpunit.xml`. 

By default, [PHPUnit prefers to use `phpcs.xml`](https://phpunit.de/manual/6.5/en/organizing-tests.html#organizing-tests.xml-configuration), so you can put your local-only modifications in there, and it will be used when running your tests locally.

We already [ignore `phpunit.xml`](https://github.com/Automattic/WPCOM-Legacy-Redirector/blob/47500d5bd46be1d1ab2628caf80ea3c1a638ff39/.gitignore#L6) in the `.gitignore`, so this new file won't get committed.

The same trick can be done with PHPCS config files as well.

Comment (ovidiul) [reply phpunit.xml.dist]: Thanks Gary for the note, done that already now. The code should be left out of this PR.

File: includes/class-utils.php [hunk 28]
```diff
@@ -0,0 +1,46 @@
...
+				return urlencode( $matches[0] );
+			},
+			$url
+		);
+
+		$parts = wp_parse_url( $encoded_url, $component );
+
+		if ( false === $parts ) {
+			throw new \InvalidArgumentException( 'Malformed URL: ' . $url );
+		}
```
Comment (GaryJones) [inline includes/class-utils.php:42]: This path is not covered by unit tests.

File: includes/class-utils.php [hunk 29]
```diff
@@ -0,0 +1,46 @@
...
+	 *                          PHP predefined constants to specify which one. Defaults
+	 *                          to -1 (= return all parts as an array).
+	 * @return array Exception on parse failure.
+	 *               Array of URL components on success; When a specific component has been
+	 *               requested: null if the component doesn't exist in the given URL; a
+	 *               string (or in the case of PHP_URL_PORT, integer) when it does.
+	 */
+	public static function mb_parse_url( $url, $component = -1 ) {
+		$encoded_url = preg_replace_callback(
+			'%[^:/@?&=#]+%usD',
```
Comment (GaryJones) [inline includes/class-utils.php]: This encoding needs a comment - why are these set of characters excluded? Why are these modifiers needed? Can you give an example of what a `$url` will be once encoded into `$encoded_url`?

Since `%` could also be used in a URL, it may make things easier to read to use the `|` character as a delimiter instead.

```suggestion
			'|[^:/@?&=#]+|usD',
```

File: includes/class-utils.php [hunk 30]
```diff
@@ -0,0 +1,46 @@
...
+	/**
+	 * UTF-8 aware parse_url() replacement.
+	 *
+	 * @throws \InvalidArgumentException Malformed URL.
+	 *
+	 * @param string $url       The URL to parse.
+	 * @param int    $component Optional. The specific component to retrieve. Use one of the
+	 *                          PHP predefined constants to specify which one. Defaults
+	 *                          to -1 (= return all parts as an array).
+	 * @return array Exception on parse failure.
```
Comment (GaryJones) [inline includes/class-utils.php]: The `array` type here isn't correct - the description says it can also be `null` or `string` or `integer`.

Also, it never _returns_ an Exception - the `@throws` line above documents that case.

File: includes/class-lookup.php [hunk 31]
```diff
@@ -103,6 +105,46 @@ public static function get_preservable_querystring_params_from_url( $url ) {
...
+		 * Get redirect data status and url based on the provided url.
+		 *
+		 * To make the redirection match, we take a full URL as $url parameter, decode it and keep
+		 * only the PATH and QUERY part of it to look for known matches.
+		 *
+		 * @param string $url URL to find redirection for, can be a full size url,
+		 *                    we do the necessary stripping inside
+		 * @return false|array We return false or an array with target redirection path
+		 *                     and redirection code
+		 */
```
Comment (GaryJones) [inline includes/class-lookup.php]: This DocBlock is indented by a tab too much.

File: includes/class-lookup.php [hunk 32]
```diff
@@ -103,6 +105,46 @@ public static function get_preservable_querystring_params_from_url( $url ) {
 		return array_intersect_key( $url_params, array_flip( $preservable_param_keys ) );
 	}
 
+		/**
+		 * Get redirect data status and url based on the provided url.
+		 *
+		 * To make the redirection match, we take a full URL as $url parameter, decode it and keep
+		 * only the PATH and QUERY part of it to look for known matches.
+		 *
+		 * @param string $url URL to find redirection for, can be a full size url,
```
Comment (GaryJones) [inline includes/class-lookup.php]: What's a "full size" URL?

Also, capitalize abbreviations:

```suggestion
		 * @param string $url URL to find redirection for, can be a full size URL,
```

File: includes/class-lookup.php [hunk 33]
```diff
@@ -103,6 +105,46 @@ public static function get_preservable_querystring_params_from_url( $url ) {
 		return array_intersect_key( $url_params, array_flip( $preservable_param_keys ) );
 	}
 
+		/**
+		 * Get redirect data status and url based on the provided url.
+		 *
+		 * To make the redirection match, we take a full URL as $url parameter, decode it and keep
```
Comment (GaryJones) [inline includes/class-lookup.php]: Avoid "we" in documenting:

```suggestion
		 * To make the redirection match, it takes a full URL as $url parameter, decode it and keep
```

Comment (GaryJones) [reply includes/class-lookup.php]: Likewise for other instances in this PR.

File: includes/class-lookup.php [hunk 34]
```diff
@@ -103,6 +105,46 @@ public static function get_preservable_querystring_params_from_url( $url ) {
...
+		 * only the PATH and QUERY part of it to look for known matches.
+		 *
+		 * @param string $url URL to find redirection for, can be a full size url,
+		 *                    we do the necessary stripping inside
+		 * @return false|array We return false or an array with target redirection path
+		 *                     and redirection code
```
Comment (GaryJones) [inline includes/class-lookup.php]:
```suggestion
		 *                     and redirection code.
```

File: includes/class-lookup.php [hunk 35]
```diff
@@ -103,6 +105,46 @@ public static function get_preservable_querystring_params_from_url( $url ) {
...
 	}
 
+		/**
+		 * Get redirect data status and url based on the provided url.
+		 *
+		 * To make the redirection match, we take a full URL as $url parameter, decode it and keep
+		 * only the PATH and QUERY part of it to look for known matches.
+		 *
+		 * @param string $url URL to find redirection for, can be a full size url,
+		 *                    we do the necessary stripping inside
```
Comment (GaryJones) [inline includes/class-lookup.php]:
```suggestion
		 *                    we do the necessary stripping inside.
```

File: includes/class-wpcom-legacy-redirector.php [hunk 36]
```diff
@@ -65,30 +66,28 @@ static function maybe_do_redirect() {
...
+			return;
 		}
 
-		$request_path = apply_filters( 'wpcom_legacy_redirector_request_path', $url );
-
-		if ( $request_path ) {
-			$redirect_uri = Lookup::get_redirect_uri( $request_path );
-			if ( $redirect_uri ) {
-				$redirect_status = apply_filters( 'wpcom_legacy_redirector_redirect_status', 301, $url );
+		// $_SERVER is being sanitized in self::normalise_url
```
Comment (GaryJones) [inline includes/class-wpcom-legacy-redirector.php]:
```suggestion
		// $_SERVER is being sanitized in self::normalise_url().
```

File: includes/class-wpcom-legacy-redirector.php [hunk 37]
```diff
@@ -65,30 +66,28 @@ static function maybe_do_redirect() {
...
-			}
+			// Third argument introduced to support the x_redirect_by header to denote WP redirect source.
+		if ( version_compare( get_bloginfo( 'version' ), '5.1.0', '>=' ) ) {
+			wp_safe_redirect( $redirect_data['redirect_uri'], $redirect_data['redirect_status'], WPCOM_LEGACY_REDIRECTOR_PLUGIN_NAME );
+		} else {
+			header( 'X-legacy-redirect: HIT' );
+			wp_safe_redirect( $redirect_data['redirect_uri'], $redirect_data['redirect_status'] );
 		}
+
+		// We need this here to make sure wp_safe_redirect redirects correctly.
```
Comment (GaryJones) [inline includes/class-wpcom-legacy-redirector.php]:
```suggestion
		// We need this here to make sure wp_safe_redirect() redirects correctly.
```

File: includes/class-wpcom-legacy-redirector.php [hunk 38]
```diff
@@ -65,30 +66,28 @@ static function maybe_do_redirect() {
...
-					header( 'X-legacy-redirect: HIT' );
-					wp_safe_redirect( $redirect_uri, $redirect_status );
-				}
+		if ( ! $redirect_data || ! isset( $redirect_data['redirect_uri'] ) ) {
+			return;
+		}
 
-				exit;
-			}
+			// Third argument introduced to support the x_redirect_by header to denote WP redirect source.
```
Comment (GaryJones) [inline includes/class-wpcom-legacy-redirector.php]:
```suggestion
		// Third argument introduced to support the x_redirect_by header to denote WP redirect source.
```

File: tests/Integration/CapabilityTest.php [hunk 39]
```diff
@@ -17,7 +17,7 @@ final class CapabilityTest extends TestCase {
 	 */
 	public function tearDown() {
 
-		(new Capability())->unregister();
+		( new Capability() )->unregister();
```
Comment (GaryJones) [inline tests/Integration/CapabilityTest.php]:
```suggestion
		(new Capability())->unregister();
```

These code style changes should be in a different PR.

File: tests/Integration/LookupTest.php [hunk 40]
```diff
@@ -0,0 +1,58 @@
...
+
+		$this->assertTrue( WPCOM_Legacy_Redirector::insert_legacy_redirect( $from_url, $to_url, false ) );
+
+		$redirect_data = Lookup::get_redirect_data( $from_url );
+
+		$this->assertEquals( $to_url, $redirect_data['redirect_uri'] );
+		$this->assertEquals( $redirect_status, $redirect_data['redirect_status'] );
+
+	}
+	/**
```
Comment (GaryJones) [inline tests/Integration/LookupTest.php:35]:
```suggestion

	/**
```

File: tests/Integration/LookupTest.php [hunk 41]
```diff
@@ -0,0 +1,58 @@
...
+	 * @dataProvider get_protected_redirect_data
+	 *
+	 * @param string $from_url        Redirect From URL.
+	 * @param string $to_url          Redirect To URL.
+	 * @param int    $redirect_status Redirect Status Code.
+	 * @return void
+	 */
+	public function test_get_redirect_uri( $from_url, $to_url, $redirect_status ) {
+
+		$this->assertTrue( WPCOM_Legacy_Redirector::insert_legacy_redirect( $from_url, $to_url, false ) );
```
Comment (GaryJones) [inline tests/Integration/LookupTest.php]: This `assertTrue()` is misplaced - this `Lookup` test class isn't about checking whether the insertion happened correctly. This line is just about the arranging.

```suggestion
		WPCOM_Legacy_Redirector::insert_legacy_redirect( $from_url, $to_url, false );
```

File: tests/Integration/LookupTest.php [hunk 42]
```diff
@@ -0,0 +1,58 @@
...
+
+	}
+	/**
+	 * Data provider for tests methods
+	 *
+	 * @return array
+	 */
+	public function get_protected_redirect_data() {
+		return array(
+			'redirect_unicode_with_query' => array(
```
Comment (GaryJones) [inline tests/Integration/LookupTest.php]: As per Example 2.6 at https://phpunit.readthedocs.io/en/9.5/writing-tests-for-phpunit.html#data-providers named providers don't need to be single underscored words.

```suggestion
			'redirect unicode characters with querystring' => array(
```

The other dataProviders in this PR should be adjusted to lose the `_` as well.

File: tests/Integration/RedirectsTest.php [hunk 43]
```diff
@@ -9,6 +9,18 @@ final class RedirectsTest extends TestCase {
 
 	public function get_redirect_data() {
 		return array(
+			'redirect_unicode_in_path'  => array(
+				// https://www.w3.org/International/articles/idn-and-iri/
+				'/JP納豆',
+				'http://example.com',
+			),
+
+			'redirect_unicode_in_path'  => array(
```
Comment (GaryJones) [inline tests/Integration/RedirectsTest.php]: Update this so that it is a different key to the one above.
```suggestion
			'redirect Arabic in path'  => array(
```

File: tests/Unit/MonkeyStubs.php [hunk 44]
```diff
@@ -0,0 +1,29 @@
...
+		parent::set_up();
+
+		Monkey\Functions\stubs(
+			array(
+				'wp_parse_url' => static function ( $url, $component ) {
+					return parse_url( $url, $component );
+				},
+				'esc_url_raw'  => static function( $value ) {
+					return $value;
+				},
```
Comment (GaryJones) [inline tests/Unit/MonkeyStubs.php]: As per https://brain-wp.github.io/BrainMonkey/docs/functions-stubs.html when there is no value/callback provided for the stub, it just returns the first param (as the call to `Monkey\Functions\stubs()` has a `null` 2nd param):

```suggestion
				'esc_url_raw', // Return 1st param unchanged.
```

File: tests/Unit/PreservableParamsTest.php [hunk 45]
```diff
@@ -85,6 +85,7 @@ public function data_get_preservable_querystring_params_from_url() {
 
 	/**
 	* @covers \Automattic\LegacyRedirector\Lookup::get_preservable_querystring_params_from_url
+	* @covers \Automattic\LegacyRedirector\Utils::mb_parse_url
```
Comment (GaryJones) [inline tests/Unit/PreservableParamsTest.php]: Why does would the test for preservable querystring params be covering the code from the Utils method?

I think you want `@uses` here.
```suggestion
	* @uses \Automattic\LegacyRedirector\Utils::mb_parse_url
```

That acknowledges that `Utils::mb_parse_url()` gets called as part of the test, but it's not the subject under test.

File: tests/Unit/RedirectsTest.php [hunk 46]
```diff
@@ -0,0 +1,69 @@
+<?php
+namespace Automattic\LegacyRedirector\Tests\Unit;
+
+use Automattic\LegacyRedirector\Tests\Unit\MonkeyStubs;
+use WPCOM_Legacy_Redirector;
+
+/**
+ * Capability Class Unit Test
+ */
+final class RedirectsTest extends MonkeyStubs {
```
Comment (GaryJones) [inline tests/Unit/RedirectsTest.php]: Let's keep the focus of this test narrow for now.

```suggestion
final class NormaliseTest extends MonkeyStubs {
```

The file name will need updating as well.

File: tests/Unit/RedirectsTest.php [hunk 47]
```diff
@@ -0,0 +1,69 @@
...
+	 * @param string $expected_schema Expected return schema.
+	 * @param string $expected_domain Expected return domain.
+	 * @param string $expected_path   Expected return path.
+	 * @param string $expected_query  Expected return query.
+	 * @return void
+	 */
+	public function test_normalise_url( $url, $expected_schema, $expected_domain, $expected_path, $expected_query ) {
+
+		$expected_return = $expected_path . ( $expected_query ? '?' . $expected_query : '' );
+		$this->assertEquals( $expected_return, WPCOM_Legacy_Redirector::normalise_url( $url ) );
```
Comment (GaryJones) [inline tests/Unit/RedirectsTest.php]:
```suggestion
		$this->assertSame( $expected_return, WPCOM_Legacy_Redirector::normalise_url( $url ) );
```

`assertSame` is a stronger check, as it also checks for type as well as value.

File: tests/Unit/RedirectsTest.php [hunk 48]
```diff
@@ -0,0 +1,69 @@
...
+	 * @covers \Automattic\LegacyRedirector\Utils::normalise_url
+	 *
+	 * @param string $url             Full URL to parse.
+	 * @param string $expected_schema Expected return schema.
+	 * @param string $expected_domain Expected return domain.
+	 * @param string $expected_path   Expected return path.
+	 * @param string $expected_query  Expected return query.
+	 * @return void
+	 */
+	public function test_normalise_url( $url, $expected_schema, $expected_domain, $expected_path, $expected_query ) {
```
Comment (GaryJones) [inline tests/Unit/RedirectsTest.php:25]: `$expected_schema` and `$expected_domain()` are provided, but never used?

File: tests/Unit/RedirectsTest.php [hunk 49]
```diff
@@ -0,0 +1,69 @@
...
+	}
+
+	/**
+	 * Data provider for tests methods for normalise_url tests
+	 *
+	 * @return array
+	 */
+	public function get_protected_redirect_data_full_url_only() {
+		return array(
+			'redirect_simple_url_no_end_slash'           => array(
```
Comment (GaryJones) [inline tests/Unit/RedirectsTest.php:44]: Needs a test for when there is a slash.

File: tests/Unit/RedirectsTest.php [hunk 50]
```diff
@@ -0,0 +1,69 @@
...
+		$this->assertEquals( $expected_return, WPCOM_Legacy_Redirector::normalise_url( $url ) );
+
+	}
+
+	/**
+	 * Data provider for tests methods for normalise_url tests
+	 *
+	 * @return array
+	 */
+	public function get_protected_redirect_data_full_url_only() {
```
Comment (GaryJones) [inline tests/Unit/RedirectsTest.php:42]: There's probably a lot more cases to go on here - probably worth pulling this test file out into its own PR.

File: tests/Unit/UtilsTest.php [hunk 51]
```diff
@@ -0,0 +1,117 @@
...
+			$path_info['host'] = '';
+		}
+		if ( ! isset( $path_info['path'] ) ) {
+			$path_info['path'] = '';
+		}
+		if ( ! isset( $path_info['query'] ) ) {
+			$path_info['query'] = '';
+		}
+
+		$this->assertTrue( is_array( $path_info ) );
```
Comment (GaryJones) [inline tests/Unit/UtilsTest.php]:
```suggestion
		$this->assertIsArray( $path_info ) );
```

https://phpunit.readthedocs.io/en/9.5/assertions.html#assertisarray

File: tests/Unit/UtilsTest.php [hunk 52]
```diff
@@ -0,0 +1,117 @@
...
+		$this->assertTrue( count( $path_info ) > 1 ? true : false );
```
Comment (GaryJones) [inline tests/Unit/UtilsTest.php]:
```suggestion
		$this->assertGreaterThan( 1, count( $path_info ) );
```

File: tests/Unit/UtilsTest.php [hunk 53]
```diff
@@ -0,0 +1,117 @@
...
+		$this->assertSame( $expected_host, $path_info['host'] );
+		$this->assertSame( $expected_path, $path_info['path'] );
+		$this->assertSame( $expected_query, $path_info['query'] );
+
```
Comment (GaryJones) [inline tests/Unit/UtilsTest.php]:
```suggestion
```

**Review by GaryJones — CHANGES_REQUESTED** [review]

File: includes/class-utils.php (hunk 28 above)
Comment (ovidiul) [reply includes/class-utils.php:42]: added a test that hails a malformed url

File: includes/class-utils.php (hunk 30 above)
Comment (ovidiul) [reply includes/class-utils.php]: fixed

File: tests/Unit/RedirectsTest.php (hunk 49 above)
Comment (ovidiul) [reply tests/Unit/RedirectsTest.php:44]: Added the test, since we are not mocking the WP_Error I need to add a method there to check if the class exists, otherwise to throw a new Error which should be triggered only with phpunit tests.

File: tests/Unit/RedirectsTest.php (hunk 50 above)
Comment (ovidiul) [reply tests/Unit/RedirectsTest.php:42]: It might be worth here to first open a github issue and then we can address that for a new PR, do you have some new tests in mind?

File: tests/Unit/bootstrap.php [hunk 54]
```diff
@@ -4,3 +4,4 @@
 require_once $vendor_dir . '/yoast/wp-test-utils/src/BrainMonkey/bootstrap.php';
 require_once $vendor_dir . '/autoload.php';
 require_once __DIR__ . '/MonkeyStubs.php';
+require_once __DIR__ . '/../../../../../wp-includes/class-wp-error.php';
```
Comment (GaryJones) [inline tests/Unit/bootstrap.php]: Need a clear linespace at the end of the file.

File: includes/class-wpcom-legacy-redirector.php [hunk 55]
```diff
@@ -217,6 +217,24 @@ public static function get_url_hash( $url ) {
 		return md5( $url );
 	}
 
+	/**
+	 * Throws new error method
+	 *
+	 * @throws \Exception $message.
+	 *
+	 * @param [type] $code    Error code.
+	 * @param [type] $message Error message.
```
Comment (GaryJones) [inline includes/class-wpcom-legacy-redirector.php]: Types are needed.

File: includes/class-wpcom-legacy-redirector.php [hunk 56]
```diff
@@ -217,6 +217,24 @@ public static function get_url_hash( $url ) {
...
+	 * @return void
+	 */
+	public static function throw_error( $code, $message ) {
+		if ( class_exists( 'WP_Error' ) ) {
+			new WP_Error( $code, $message );
```
Comment (GaryJones) [inline includes/class-wpcom-legacy-redirector.php]: Does this need a `return` at the start of the line?

Comment (ovidiul) [reply includes/class-wpcom-legacy-redirector.php]: Yes, fixed now! Should we push this method to Utils class maybe and add a test for it?

File: includes/class-utils.php (hunk 29 above)
Comment (ovidiul) [reply includes/class-utils.php]: Delimiter characters replaced. 

Added method description update with examples, as per https://developers.google.com/maps/documentation/urls/url-encoding , we have a larger list of reserved chars for URLs which we should not encode, so I've update the `preg_replace_callback` list to reflect that. 

Also, should we care about unsafe chars at this stage https://developers.google.com/maps/documentation/urls/url-encoding#common-characters-that-need-encoding ?

File: tests/Unit/bootstrap.php (hunk 54 above)
Comment (ovidiul) [reply tests/Unit/bootstrap.php]: This is not needed anymore, we can throw an exception when WP_Error is not available.

File: tests/Unit/RedirectsTest.php (hunk 48 above)
Comment (ovidiul) [reply tests/Unit/RedirectsTest.php:25]: They are used now as below.

File: tests/Integration/LookupTest.php (hunk 40 above)
Comment (ovidiul) [reply tests/Integration/LookupTest.php:35]: this is fixed, not sure why it doesn't resolve itself?

Comment (GaryJones) [reply tests/Integration/LookupTest.php:35]: Because comments don't resolve themselves :-)

File: tests/Unit/RedirectsTest.php [hunk 57]
```diff
@@ -0,0 +1,81 @@
...
+				'',
+			),
+			'redirect_simple_url_with_end_slash'         => array(
+				'https://www.example1.org/',
+				'https',
+				'www.example1.org',
+				'/',
+				'',
+			),
+			'redirect_normal_path_with_multiple_slashes' => array(
```
Comment (GaryJones) [inline tests/Unit/RedirectsTest.php]: Let's find a different name than "normal", as that implies that non-latin ASCII is not "normal".

**Review by GaryJones — APPROVED** [review]
Approving with one or two suggestions top consider.

I also think that the Unit tests and Integration tests have a fair bit of overlap, which means that a future interaction may look at removing them, but fine to include the for now.

File: tests/Unit/RedirectsTest.php (hunk 57 above)
Comment (ovidiul) [reply tests/Unit/RedirectsTest.php]: fixed the naming as `redirect_ascii_path_with_multiple_slashes`

**Review by GaryJones — APPROVED** [review]

**Comment by GaryJones** [comment]
Other than the conflicts, having looked at this again with fresh eyes, I think there are a lot of parts that could and should be pulled out into fresh PRs as iterative steps to improve the testing / resilience of this plugin, culminating with a final PR that actually does the needed fix. Things like Normalize tests, Utils::mb_parse_url etc.

**Comment by GaryJones** [comment]
I started splitting this out, but the more I looked and tested locally, the more it made sense to just double-checked the PR worked as is, and it does!
